---
weight: 2
title: "Git and GitHub"
output: html_document
---

One of the defining principles behind how this course teaches computing is that 
everything the instructor and the students produce should be reproducible -- how 
you get a result is just as important as the result itself. Implicit in the idea 
of reproducibility is collaboration, the code you produce is documentation of 
the process and it is critical to share it (even if only with yourself in the 
future). One of the goals of this course is to teach students tools that make 
this documentation and collaboration as robust and painless as possible. This is 
best accomplished with a distributed version control system like git.

This course adopts a wtop down approach to teaching git -- students are 
*required* to use it for *all* assignments. These type of tools tend to suffer 
from delayed gratification as when they are first introduced students view them 
as a clunky addition to their workflow and it is not until weeks or even months 
later that they experience the value first hand. 


----

And here is a link to [ghclass vignette](https://rundel.github.io/ghclass/articles/ghclass.html).

----

## Instructions for assignment getting started and "submission" via Git

Here are the steps for getting started:

- Go to the classroom GitHub organization and grab the link of the assignment 
repo.
- Start a new RStudio project from Git cloning this repository
- Make any changes needed as outlined by the tasks you need to complete for the 
assignment
- Make sure all your code chunks are informatively named, and these labels are 
not repeated
- Periodically commit changes (the more often the better, for example, once per 
each new task)
- Push all your changes back to your GitHub repo

and voila, you're done! Once you push your changes back you do not need to do 
anything else to "submit" your work. And you can of course push multiple times 
throughout the assignment. At the time of the deadline we will take whatever 
is in your repo and consider it your final submission, and grade the state of 
your work at that time (which means even if you made mistakes before then, 
you wouldn't be penalized for them as long as the final state of your work is 
correct).

-----

## Continuous integration and badges

Something new on this homework, and going forward on class assignments. Each time you push to GitHub a continuous integration tool (called wercker) will check to make sure your Rmd knits successfully. If it does, you'll be able to see a badge on the README of your repo that says "build passing" (in green). If it fails, it'll say "build failing" (in orange). If the build is failing you will need to fix your Rmd so that it knits without any errors and then push again. Some tips:

- You should avoid leaving your repo in a failing stage. 
- You can click on the "build failing" badge to get more information.
- A "build passing" badge is not guarantee that your work is correct, but instead just that your Rmd file knits.

----

lab getting started

# Getting started

- Go to the course organization on GitHub: https://github.com/Sta199-S18.

- Find the repo starting with `lab-03` and that has your team name at the end (this should be the only `lab-03` repo available to you).

- In the repo, click on the green **Clone or download** button, select **Use HTTPS** (this might already be selected by default, and if it is, you'll see the text **Clone with HTTPS** as in the image below). Click on the clipboard icon to copy the repo URL.

- Go to RStudio Cloud and into the course workspace. Create a **New Project from Git Repo**. You will need to click on the down arrow next to the **New Project** button to see this option.

- Copy and paste the URL of your assignment repo into the dialog box:

- Hit OK, and you're good to go!

----

Also for labs

# Housekeeping

## Git configuration

```{marginfigure}
Your email address is the address tied to your GitHub account and your name should be first and last name.
```

- Go to the *Terminal* pane
- Type the following two lines of code, replacing the information in the quotation marks with your info.

```{bash eval=FALSE}
git config --global user.email "your email"
git config --global user.name "your name"
```

To confirm that the changes have been implemented, run the following:

```{bash eval=FALSE}
git config --global user.email
git config --global user.name
```

## Password caching

If you would like your git password cached for a week for this project, type the following in the Terminal:

```{bash eval=FALSE}
git config --global credential.helper 'cache --timeout 604800'
```

## Project name: 

Currently your project is called *Untitled Project*. Update the name of your project to be "Lab 05 - Simpson's paradox".

# Warm up

**Pick one team member to complete the steps in this section while the others contribute to the discussion but do not actually touch the files on their computer.**

Before we introduce the data, let's warm up with some simple exercises.

## YAML: 

Open the R Markdown (Rmd) file in your project, change the author name to your **team** name, and knit the document.

## Commiting and pushing changes:

- Go to the **Git** pane in your RStudio. 
- View the **Diff** and confirm that you are happy with the changes.
- Add a commit message like "Update team name" in the **Commit message** box and hit **Commit**.
- Click on **Push**. This will prompt a dialogue box where you first need to enter your user name, and then your password.

## Pulling changes:

Now, the remaining team members who have not been concurrently making these changes on their projects should click on the **Pull** button in their Git pane and observe that the changes are now reflected on their projects as well.
