---
weight: 1
title: "Setup"
output: html_document
---

If you are already an R and RStudio user, you are probably already ready to go.
We recommend that you upgrade to the latest versions of R and RStudio.

If you are not yet an R user, you will want to download and install R and 
RStudio. To download R, go to CRAN, the **c**omprehensive **R** **a**rchive 
**n**etwork. CRAN is composed of a set of mirror servers distributed around the 
world and is used to distribute R and R packages. Don't try and pick a mirror 
that's close to you: instead use the cloud mirror, <https://cloud.r-project.org>, 
which automatically figures it out for you. You can download and install RStudio 
from <http://www.rstudio.com/download>.

You can also access RStudio on the cloud at [RStudio Cloud](http://rstudio.cloud/).

All student facing materials for this course have been organized in an RStudio 
Cloud workspace [here](https://rstudio.cloud/spaces/1655/projects). Soon you will 
have the option to copy that workspace and use it to organize assignments and 
assessments.
