# Exploring data {#exploring-data}

This unit focuses on data visualization and data wrangling.
Specifically we cover fundamentals of data and data visualization, confounding variables, and Simpson's paradox as well as the concept of tidy data, data import, data cleaning, and data curation.
We end the unit with web scraping and introduce the idea of iteration in preparation for the next unit.
Also in this unit students are introduced to the toolkit: R, RStudio, R Markdown, Git, and GitHub.

::: {.rstudio-cloud}
The RStudio Cloud workspace for Data Science Course in a Box project is [here](https://rstudio.cloud/spaces/1655/join?access_code=5rdjusfIYF5iI0Gum2vNsBDLdtdnIEELBkf2EivK).
You can join the workspace and play around with the application exercises.
:::

## Slides & application exercises

### Visualising data

::: {.slide-deck}
**Unit 2 - Deck 1: Data and visualisation**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d01-data-viz/u2-d01-data-viz.html#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d01-data-viz)
:::

::: {.video}
[Video](https://youtu.be/FddF4b_GuTI)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 2: Visualising data with ggplot2**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d02-ggplot2/u2-d02-ggplot2.html#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d02-ggplot2)
:::

::: {.video}
[Video](https://youtu.be/s2NF2J36ljE)
:::

::: {.reading}
R4DS :: [Chp 3 - Data visualization](https://r4ds.had.co.nz/data-visualisation.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 3: Visualising numerical data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d03-viz-num/u2-d03-viz-num.html#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d03-viz-num)
:::

::: {.video}
[Video](https://youtu.be/waBabVTI8ec)
:::

::: {.reading}
IMS :: [Sec 2.1 - Exploring numerical data](https://openintro-ims.netlify.app/summarizing-visualizing-data.html#numerical-data)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 4: Visualising categorical data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d04-viz-cat/u2-d04-viz-cat.html#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d04-viz-cat)
:::

::: {.video}
[Video](https://youtu.be/21h3rEO8k2E)
:::

::: {.reading}
IMS :: [Sec 2.2 - Exploring categorical data](https://openintro-ims.netlify.app/summarizing-visualizing-data.html#categorical-data)
:::
:::

::: {.application-exercise}
**StarWars + Dataviz**

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-03-starwars-dataviz/ae-03-starwars-dataviz.Rmd)
:::

::: {.video}
[Video](https://youtu.be/3UaLPtCKkXQ)
:::
:::

### Wrangling and tidying data

::: {.slide-deck}
**Unit 2 - Deck 5: Tidy data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d05-tidy-data/u2-d05-tidy-data#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d05-tidy-data)
:::

::: {.video}
[Video](https://youtu.be/Ux85eR3h9hw)
:::

::: {.reading}
JSS :: [Tidy data](https://www.jstatsoft.org/article/view/v059i10)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 6: Grammar of data wrangling**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d06-grammar-wrangle/u2-d06-grammar-wrangle#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d06-grammar-wrangle)
:::

::: {.video}
[Video](https://youtu.be/ZCaYBES_VEk)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 7: Working with a single data frame**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d07-single-df/u2-d07-single-df#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d07-single-df)
:::

::: {.video}
[Video](https://youtu.be/0229Uq2hkJo)
:::

::: {.reading}
R4DS :: [Chp 5 - Data transformation](https://r4ds.had.co.nz/transform.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 8: Working with multiple data frames**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d08-multi-df/u2-d08-multi-df#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d08-multi-df)
:::

::: {.video}
[Video](https://youtu.be/VdV5ABsaf5Y)
:::

::: {.reading}
R4DS :: [Chp 13 - Relational data](https://r4ds.had.co.nz/relational-data.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 9: Tidying data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d09-tidying/u2-d09-tidying#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d09-tidying)
:::

::: {.video}
[Video](https://youtu.be/x3KM5uxaFdI)
:::

::: {.reading}
R4DS :: [Chp 12 - Tidy data](https://r4ds.had.co.nz/tidy-data.html)
:::
:::

::: {.application-exercise}
**Hotels + Data wrangling**

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-04-hotels-datawrangling/ae-04-hotels-datawrangling.Rmd)
:::

::: {.video}
[Video](https://youtu.be/BXlOd4EYQrI)
:::
:::

### Importing and recoding data

### Communicating data science results effectively

### Web scraping and programming

```{=html}
<!-- 

::: {.slide-deck}
**Unit 1 - Deck 8: Data types and recoding**

[[Slides]](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d08-data-types/u1_d08-data-types.html#1) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u1_d08-data-types)

::: {.application-exercise}
[Hotels + Data types](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-06-hotels-datatypes)
:::

::: {.reading}
-   [R4DS :: Chp 20.2 - Vector basics](https://r4ds.had.co.nz/vectors.html#vector-basics)
-   [R4DS :: Chp 20.3 - Important types of atomic vector](https://r4ds.had.co.nz/vectors.html#important-types-of-atomic-vector)
-   [R4DS :: Chp 15 - Factors](https://r4ds.had.co.nz/factors.html)
-   [R4DS :: Chp 16.2 - Creating date/times](https://r4ds.had.co.nz/dates-and-times.html#creating-datetimes)
-   [R4DS :: Chp 16.3 - Date-time components](https://r4ds.had.co.nz/dates-and-times.html#date-time-components)
:::
:::

::: {.slide-deck}
**Unit 1 - Deck 9: Importing data**

[[Slides]](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d09-import-data/u1_d09-import-data.html#1) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u1_d09-import-data)

::: {.application-exercise}
[Nobels & Sales + Data import](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-07-nobels-sales-dataimport)
:::

::: {.reading}
[R4DS :: Chp 11 - Data import](https://r4ds.had.co.nz/data-import.html)
:::
:::

::: {.slide-deck}
**Unit 1 - Deck 10: Tips for effective data visualization**

[[Slides]](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d10-effective-dataviz/u1_d10-effective-dataviz.html#1) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u1_d10-effective-dataviz)

::: {.reading}
[IMS :: Sec 2.3 - Effective data visualization](https://openintro-ims.netlify.app/summarizing-visualizing-data.html#effective-data-visualization)
:::
:::

::: {.slide-deck}
**Unit 1 - Deck 11: Scientific studies and confounding**

[[Slides]](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d11-studies-confounding/u1_d11-studies-confounding.html#1) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u1_d11-studies-confounding)

::: {.reading}
-   [IMS :: Sec 1.3 - Sampling principles and strategies](https://openintro-ims.netlify.app/getting-started-with-data.html#sampling-principles-strategies)
-   [IMS :: Sec 1.4 - Experiments](https://openintro-ims.netlify.app/getting-started-with-data.html#experiments)
:::
:::

::: {.slide-deck}
**Unit 1 - Deck 12: Communicating data science results effectively**

[[Slides]](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d12-effective-communication/u1_d12-effective-communication.html#1) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u1_d12-effective-communication)
:::

::: {.slide-deck}
**Unit 1 - Deck 13: Web scraping**

[[Slides]](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d13-webscraping/u1_d13-webscraping.html#1) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u1_d13-webscraping)

::: {.application-exercise}
[IMDB + Web scraping](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-08-imdb-webscraping)
:::
:::

::: {.slide-deck}
**Unit 1 - Deck 14: Functions and iteration**

[[Slides]](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d14-functions-iteration/u1_d14-functions-iteration.html#1) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u1_d14-functions-iteration)

::: {.application-exercise}
[University of Edinburgh Art + Functions](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-09-uoeart-functions)
:::

::: {.reading}
-   [R4DS :: Chp 19 - Functions](https://r4ds.had.co.nz/functions.html)
-   [R4DS :: Sec 21.5 - The map functions](https://r4ds.had.co.nz/iteration.html#the-map-functions)
:::
:::

-->
```
## Labs

::: {.lab}
**Lab 1: Hello R**

Introduction to R, R Markdown, Git, and GitHub

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/lab-instructions/lab-01/lab-01-hello-r.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-01) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/labs/lab-01-hello-r)
:::

::: {.lab}
**Lab 2: Plastic waste**

Introduction to working with data in R with the tidyverse

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/lab-instructions/lab-02/lab-02-plastic-waste.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-02) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/labs/lab-02-plastic-waste)
:::

::: {.lab}
**Lab 3: Nobel laureates**

Data wrangling and tidying

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/lab-instructions/lab-03/lab-03-nobel-laureates.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-03) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/labs/lab-03-nobel-laureates)
:::

::: {.lab}
**Lab 4: La Quinta is Spanish for 'next to Denny's', Pt. 1**

Visualizing spatial data

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/lab-instructions/lab-04/lab-04-viz-sp-data.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-04)
:::

::: {.lab}
**Lab 5: La Quinta is Spanish for 'next to Denny's', Pt. 2**

Wrangling spatial data

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/lab-instructions/lab-05/lab-05-wrangle-sp-data.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-05)
:::

::: {.lab}
**Lab 6: Ugly charts**

Critiquing and improving data visualisations

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/lab-instructions/lab-06/lab-06-ugly-charts.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-06) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/labs/lab-06-ugly-charts)
:::

::: {.lab}
**Lab 7: Simpson's paradox**

Data visualisation, confounding, multivariable relationships

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/lab-instructions/lab-07/lab-07-simpsons-paradox.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-07) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/labs/lab-07-simpsons-paradox)
:::

::: {.lab}
**Lab 8: University of Edinburgh Art Collection**

Web scraping, function, iteration

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/lab-instructions/lab-08/lab-08-uoe-art.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-08) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/labs/lab-08-uoe-art)
:::

## Homework assignments

::: {.homework}
**HW 1: Edinburgh Airbnb rentals**

Introduction to working with data in R with the tidyverse

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/hw-instructions/hw-01/hw-01-airbnb-edi.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-01) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/assignments/hw-01-airbnb-edi)
:::

::: {.homework}
**HW 2: North Carolina bike crashes**

Data wrangling, tidying, and visualization

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/hw-instructions/hw-02/hw-02-bike-crash.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-02) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/assignments/hw-02-bike-crash)
:::

::: {.homework}
**HW 3: What should I major in?**

Data wrangling, summarizing, and visualization

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/hw-instructions/hw-03/hw-03-college-majors.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-03) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/assignments/hw-03-college-majors)
:::

::: {.homework}
**HW 4: Legos and instructors**

Data wrangling, summarizing, and visualization

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/hw-instructions/hw-04/hw-04-legos-instructors.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-04) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/assignments/hw-04-legos-instructors)
:::

::: {.homework}
**HW 5: Money in politics**

Web scraping, functions, and iteration

[[Instructions]](https://rstudio-education.github.io/datascience-box/course-materials/hw-instructions/hw-05/hw-05-money-in-politics.html) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-05) [[Starter]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/assignments/hw-05-money-in-politics)
:::
