# (PART) Course content {.unnumbered}

# Hello world {#hello-world}

I recommend starting the class off right, devoting more of the class time to introducing the course content instead of the course policies.
And get students doing something with data as quickly as possible!
A personal goal of mine is to get students to produce their first data visualization within the first 10 minutes of class.
The application exercise in this lecture is one way of achieving this goal.
Slides for Day One of class are provided below.

Note that getting students computing on Day One in class requires that they come to class equipped with a laptop or that you're holding your course online or in a computer lab.
They do not need to do any preparation ahead of time, just need internet access.
As outlined in the slides, give them a link to your RStudio Cloud workspace and get them started working on the application exercise you put together for them.

<iframe width="560" height="315" style="border:1px solid #80D4E6; margin-top:10px; margin-bottom:10px;" src="https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d01-welcome/u1_d01-welcome.html#1" frameborder="0">

</iframe>

You can view the slides in full screen as well as access their source code.
Along with the slides for this lesson, I'm providing two options for such an activity.
Note that one of them uses COVID-19 data and depending on where, when, and to whom you're teaching, working with these data might not be the most pleasant experience for all students.
Please make sure to consider this before using this activity.

::: {.slide-deck}
**Unit 1 - Deck 1: Welcome**

[[Slides]](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d01-welcome/u1_d01-welcome.html#1) [[Source]](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u1_d01-welcome)

::: {.application-exercise}
[Option 1 - UN Votes](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-01a-un-votes)
:::

::: {.application-exercise}
[Option 2 - COVID-19](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-01b-covid)
:::
:::

::: {.rstudio-cloud}
The RStudio Cloud workspace for Data Science Course in a Box project is [here](https://rstudio.cloud/spaces/1655/join?access_code=5rdjusfIYF5iI0Gum2vNsBDLdtdnIEELBkf2EivK).
You can join the workspace and play around with sample application exercises.
:::
