---
title: "Hello world"
---

I recommend starting the class off right, devoting more of the class time to introducing the course content instead of the course policies.
And get students doing something with data as quickly as possible!
A personal goal of mine is to get students to produce their first data visualization within the first 10 minutes of class.
The application exercise in this lecture is one way of achieving this goal.
Slides for Day One of class are provided below.

Note that getting students computing on Day One in class requires that they come to class equipped with a laptop or that you're holding your course online or in a computer lab.
If teaching online, this is resolved automatically, of course.
They do not need to do any preparation ahead of time, just need internet access.
As outlined in the slides, give them a link to your RStudio Cloud workspace and get them started working on the application exercise you put together for them.
There are two options for a day one application exercise.
Note that one of them uses COVID-19 data and depending on where, when, and to whom you're teaching, working with these data might not be the most pleasant experience for all students.
Please make sure to consider this before using this activity.

::: rstudio-cloud
The RStudio Cloud workspace for Data Science Course in a Box project is [here](https://rstudio.cloud/spaces/1655/join?access_code=5rdjusfIYF5iI0Gum2vNsBDLdtdnIEELBkf2EivK).
You can join the workspace and play around with the sample application exercises.
:::

## Slides, videos, and application exercises

::: slide-deck
**Unit 1 - Deck 1: Welcome**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u1-d01-welcome/u1-d01-welcome.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u1-d01-welcome)
:::

::: video
[Video](https://youtu.be/OJ1xR0ObhIw)
:::
:::

::: application-exercise
**First dataviz**

> **Option 1 - UN Votes**
>
> ::: source
> [Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-01a-un-votes/unvotes.qmd)
> :::
>
> ::: video
> [Video](https://youtu.be/r-uTBEclM1E)
> :::

> **Option 2 - COVID-19**
>
> ::: source
> [Source](https://github.com/rstudio-education/datascience-box/blob/master/course-materials/application-exercises/ae-01b-covid/covid.qmd)
> :::
:::

::: slide-deck
**Unit 1 - Deck 2: Meet the toolkit - Programming**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u1-d02-toolkit-r/u1-d02-toolkit-r.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u1-d02-toolkit-r)
:::

::: video
[Video](https://youtu.be/mTAZLFcpnLI)
:::

::: reading
-   R4DS :: [Chp 2 - Introduction](https://r4ds.had.co.nz/explore-intro.html)
-   IMS :: [Sec 1.1 & 1.2 - Case study & Data basics](https://openintro-ims.netlify.app/data-hello.html)
:::
:::

::: application-exercise
**Bechdel + R Markdown**

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-02-bechdel-rmarkdown/bechdel.qmd)
:::
:::

::: slide-deck
**Unit 1 - Deck 3: Meet the toolkit - Version control and collaboration**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u1-d03-toolkit-git/u1-d03-toolkit-git.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u1-d03-toolkit-git)
:::

::: video
[Video](https://youtu.be/124DQasLyNQ)
:::
:::
