---
title: "Making rigorous conclusions"
---

In this part we introduce modelling and statistical inference for making data-based conclusions.
We discuss building, interpreting, and selecting models, visualizing interaction effects, and prediction and model validation.
Statistical inference is introduced from a simulation based perspective, and the Central Limit Theorem is discussed very briefly to lay the foundation for future coursework in statistics.

::: rstudio-cloud
The RStudio Cloud workspace for Data Science Course in a Box project is [here](https://rstudio.cloud/spaces/1655/join?access_code=5rdjusfIYF5iI0Gum2vNsBDLdtdnIEELBkf2EivK).
You can join the workspace and play around with the sample application exercises.
:::

## Slides, videos, and application exercises

### Modelling data

::: slide-deck
**Unit 4 - Deck 1: The language of models**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d01-language-of-models/u4-d01-language-of-models.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d01-language-of-models)
:::

::: video
[Video](https://youtu.be/MWkkvDopBKc)
:::
:::

::: slide-deck
**Unit 4 - Deck 2: Fitting and interpreting models**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d02-fitting-interpreting-models/u4-d02-fitting-interpreting-models.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d02-fitting-interpreting-models)
:::

::: video
[Video](https://youtu.be/69U92Q3pwnA)
:::

::: reading
IMS :: [Chp 7 - Linear regression with a single predictor](https://openintro-ims.netlify.app/model-slr.html)
:::
:::

::: slide-deck
**Unit 4 - Deck 3: Modelling nonlinear relationships**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d03-modeling-nonlinear-relationships/u4-d03-modeling-nonlinear-relationships.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d03-modeling-nonlinear-relationships)
:::

::: video
[Video](https://youtu.be/j4MZ6ZdHnHg)
:::
:::

::: slide-deck
**Unit 4 - Deck 4: Models with multiple predictors**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d04-model-multiple-predictors/u4-d04-model-multiple-predictors.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d04-model-multiple-predictors)
:::

::: video
[Video](https://youtu.be/mjkNabD4oi4)
:::

::: reading
IMS :: [Chp 8 - Linear regression with multiple predictors](https://openintro-ims.netlify.app/model-mlr.html)
:::
:::

::: slide-deck
**Unit 4 - Deck 5: More models with multiple predictors**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d05-more-model-multiple-predictors/u4-d05-more-model-multiple-predictors.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d05-more-model-multiple-predictors)
:::

::: video
[Video](https://youtu.be/nJAYRnLPb10)
:::
:::

### Classification and model building

::: slide-deck
**Unit 4 - Deck 6: Logistic regression**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d06-logistic-reg/u4-d06-logistic-reg.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d06-logistic-reg)
:::

::: video
[Video](https://youtu.be/AidXFYSYfJg)
:::

::: reading
IMS :: [Chp 9 - Logistic regression](https://openintro-ims.netlify.app/model-logistic.html)
:::
:::

::: slide-deck
**Unit 4 - Deck 7: Prediction and overfitting**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d07-prediction-overfitting/u4-d07-prediction-overfitting.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d07-prediction-overfitting)
:::

::: video
[Video](https://youtu.be/Qd4lu_Lmwi0)
:::

::: reading
tidymodels :: [Build a model](https://www.tidymodels.org/start/models/)
:::
:::

::: slide-deck
**Unit 4 - Deck 8: Feature engineering**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d08-feature-engineering/u4-d08-feature-engineering.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d08-feature-engineering)
:::

::: video
[Video](https://youtu.be/wZt9ab4jBZ4)
:::

::: reading
tidymodels :: [Preprocess your data with recipes](https://www.tidymodels.org/start/recipes/)
:::
:::

### Model validation

::: slide-deck
**Unit 4 - Deck 9: Cross validation**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d09-cross-validation/u4-d09-cross-validation.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d09-cross-validation)
:::

::: video
[Video](https://youtu.be/L1KfIISmUT4)
:::

::: reading
tidymodels :: [Evaluate your model with resampling](https://www.tidymodels.org/start/resampling/)
:::
:::

::: application-exercise
**The Office + Feature engineering, Pt. 1**

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-09-feat-eng-cv/theoffice.qmd)
:::

::: video
[Video](https://youtu.be/qsUYstdN4LQ)
:::
:::

::: application-exercise
**The Office + Cross validation, Pt. 2**

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/application-exercises/ae-09-feat-eng-cv/theoffice.qmd)
:::

::: video
[Video](https://youtu.be/WstIr94Fdjc)
:::
:::

### Uncertainty quantification

::: slide-deck
**Unit 4 - Deck 10: Quantifying uncertainty**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d10-quantify-uncertainty/u4-d10-quantify-uncertainty.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d10-quantify-uncertainty)
:::

::: video
[Video](https://youtu.be/LYpKrtZmQtI)
:::
:::

::: slide-deck
**Unit 4 - Deck 11: Bootstrapping**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d11-bootstrap/u4-d11-bootstrap.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d11-bootstrap)
:::

::: video
[Video](https://youtu.be/bdqpI3iVOso)
:::

::: reading
IMS :: [Chp 12 - Confidence intervals with bootstrapping](https://openintro-ims.netlify.app/foundations-bootstrapping.html)
:::
:::

::: slide-deck
**Unit 4 - Deck 12: Hypothesis testing**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d12-hypothesis-testing/u4-d12-hypothesis-testing.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d12-hypothesis-testing)
:::

::: reading
[IMS :: Chp 11 - Hypothesis testing with randomization](https://openintro-ims.netlify.app/foundations-randomization.html)
:::
:::

::: slide-deck
**Unit 4 - Deck 13: Inference overview**

::: slides
[Slides](https://datasciencebox.org/course-materials/_slides/u4-d13-inference-overview/u4-d13-inference-overview.html#1)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/main/course-materials/_slides/u4-d13-inference-overview)
:::
:::

## Labs

::: lab
**Lab 10: Grading the professor, Pt. 1**

Fitting and interpreting simple linear regression models

::: instructions
[Instructions](https://datasciencebox.org/course-materials/lab-instructions/lab-10/lab-10-slr-course-evals.html)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-10)
:::

::: starter
[Starter](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/lab/lab-10-slr-course-evals)
:::
:::

::: lab
**Lab 11: Grading the professor, Pt. 2**

Fitting and interpreting multiple linear regression models

::: instructions
[Instructions](https://datasciencebox.org/course-materials/lab-instructions/lab-11/lab-11-mlr-course-evals.html)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-11)
:::

::: starter
[Starter](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/lab/lab-11-mlr-course-evals)
:::
:::

::: lab
**Lab 12: Smoking while pregnant**

Constructing confidence intervals, conducting hypothesis tests, and interpreting results in context of the data

::: instructions
[Instructions](https://datasciencebox.org/course-materials/lab-instructions/lab-12/lab-12-inference-smoking.html)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/lab-instructions/lab-12)
:::

::: starter
[Starter](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/lab/lab-12-inference-smoking)
:::
:::

## Homework assignments

::: homework
**HW 7: Bike rentals in DC**

Exploratory data analysis and fitting and interpreting models

::: instructions
[Instructions](https://datasciencebox.org/course-materials/hw-instructions/hw-07/hw-07-bike-rentals-dc.html)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-07)
:::

::: starter
[Starter](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/hw/hw-07-bike-rentals-dc)
:::
:::

::: homework
**HW 8: Exploring the GSS**

Fitting and interpreting models

::: instructions
[Instructions](https://datasciencebox.org/course-materials/hw-instructions/hw-08/hw-08-exploring-gss.html)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-08)
:::

::: starter
[Starter](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/hw/hw-08-exploring-gss)
:::
:::

::: homework
**HW 9: Modelling the GSS**

Model validation and inference

::: instructions
[Instructions](https://datasciencebox.org/course-materials/hw-instructions/hw-09/hw-09-modeling-gss.html)
:::

::: source
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/hw-instructions/hw-09)
:::

::: starter
[Starter](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters/hw/hw-09-modeling-gss)
:::
:::
