# Schedule {#schedule}

There are a lot of materials in Data Science Course in a Box, which allows instructors to pick and choose what they want depending on the length of the course they're teaching, their audience, and the curriculum within which the course is placed.
The following are two options for course schedules, one for a 11-week course and the other for a 15-week course.

## 11-week schedule

+-------+--------+---------------------------------------------------------------+--------------------------+
| Unit  | Week   | Title                                                         | Type                     |
+=======+========+===============================================================+==========================+
| 1     | 1      | Welcome to data science!                                      | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 1     | 1      | Meet the toolkit: Programming                                 | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 1     | 1      | Meet the toolkit: Version control and collaboration           | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 1     | 1      | Hello R                                                       | Lab                      |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 1     | 1      | Pet names                                                     | Homework                 |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **2**  | **Data and visualisation**                                    | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **2**  | **Visualising data with ggplot2**                             | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **2**  | **Visualising numerical data**                                | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **2**  | **Visualising categorical data**                              | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **2**  | **StarWars + Dataviz**                                        | **Application exercise** |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **2**  | **Plastic waste**                                             | **Lab**                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **2**  | **Airbnb listings in Edinburgh**                              | **Homework**             |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 3      | Tidy data                                                     | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 3      | Grammar of data wrangling                                     | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 3      | Working with a single data frame                              | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 3      | Working with multiple data frames                             | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 3      | Tidying data                                                  | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 3      | Hotels + Data wrangling                                       | Application exercise     |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 3      | Nobel laureates                                               | Lab                      |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 3      | Road traffic accidents                                        | Homework                 |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **4**  | **Data types**                                                | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **4**  | **Data classes**                                              | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **4**  | **Importing data**                                            | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **4**  | **Recoding data**                                             | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **4**  | **Hotels + Data types**                                       | **Application exercise** |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **4**  | **Nobels + Sales + Data import**                              | **Application exercise** |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **4**  | **Option 1: La Quinta is Spanish for next to Denny's, Pt. 1** | **Lab**                  |
|       |        |                                                               |                          |
|       |        | **Option 2: La Quinta is Spanish for next to Denny's, Pt. 2** |                          |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **4**  | **College majors**                                            | **Homework**             |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 5      | Tips for effective data visualization                         | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 5      | Brexit + Telling stories with dataviz                         | Application exercise     |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 5      | Scientific studies and confounding                            | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 5      | Simpson's paradox                                             | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 5      | Doing data science                                            | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 5      | Option 1: Take a sad plot and make it better                  | Lab                      |
|       |        |                                                               |                          |
|       |        | Option 2: Simpson's paradox                                   |                          |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 2     | 5      | Legos                                                         | Homework                 |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **6**  | **Web scraping**                                              | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **6**  | **Scraping top 250 movies on IMDB**                           | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **6**  | **Web scraping considerations**                               | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **6**  | **IMDB + Web scraping**                                       | **Application exercise** |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **6**  | **Functions**                                                 | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **6**  | **Iteration**                                                 | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **6**  | **University of Edinburgh Art Collection**                    | **Lab**                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **2** | **6**  | **Money in politics**                                         | **Homework**             |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 3     | 7      | Misrepresentation                                             | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 3     | 7      | Data privacy                                                  | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 3     | 7      | Algorithmic bias                                              | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 3     | 7      | Conveying the right message through visualisation             | Lab                      |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 3     | 7      | Project proposals                                             | Project                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **8**  | **Fitting and interpreting models**                           | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **8**  | **Modelling nonlinear relationships**                         | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **8**  | **Models with multiple predictors**                           | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **8**  | **More models with multiple predictors**                      | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **8**  | **Grading the professor, Pt 1**                               | **Lab**                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **8**  | **Option 1: Bike rentals in DC**                              | **Homework**             |
|       |        |                                                               |                          |
|       |        | **Option 2: Peer review of project proposals**                |                          |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 4     | 9      | Logistic regression                                           | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 4     | 9      | Prediction and overfitting                                    | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 4     | 9      | Feature engineering                                           | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 4     | 9      | Grading the professor, Pt 1                                   | Lab                      |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 4     | 9      | Exploring the GSS                                             | Homework                 |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **10** | **Cross validation**                                          | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **10** | **The Office, Part 1**                                        | **Application exercise** |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **10** | **The Office, Part 2**                                        | **Application exercise** |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **10** | **Quantifying uncertainty**                                   | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **10** | **Bootstrapping**                                             | **Lecture**              |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **10** | **Option 1: Smoking during pregnancy**                        | **Lab**                  |
|       |        |                                                               |                          |
|       |        | **Option 2: Work on projects**                                |                          |
|       |        |                                                               |                          |
|       |        | **Option 3: Collaboration on GitHub**                         |                          |
+-------+--------+---------------------------------------------------------------+--------------------------+
| **4** | **10** | **Modelling the GSS**                                         | **Homework**             |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 5     | 11     | Text analysis                                                 | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 5     | 11     | Comparing texts                                               | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 5     | 11     | Interactive web apps                                          | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 5     | 11     | Machine learning                                              | Lecture                  |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 5     | 11     | Project presentations                                         | Lab                      |
+-------+--------+---------------------------------------------------------------+--------------------------+
| 5     | 11     | Wrap up                                                       | Homework                 |
+-------+--------+---------------------------------------------------------------+--------------------------+

## 15-week schedule

+-------+--------+-------------------------------------------------------+--------------+
| Unit  | Week   | Title                                                 | Type         |
+=======+========+=======================================================+==============+
| 1     | 1      | Welcome to data science!                              | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 1      | Meet the toolkit                                      | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 1      | Hello R                                               | Lab          |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 1      | Edinburgh Airbnb rentals                              | Homework     |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **2**  | **Data and visualization**                            | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **2**  | **Building plots for various data types**             | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **2**  | **Plastic waste**                                     | **Lab**      |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **2**  | **North Carolina bike crashes**                       | **Homework** |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 3      | Tidy data and data wrangling                          | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 3      | Joining data from multiple sources                    | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 3      | Nobel laureates                                       | Lab          |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 3      | What should I major in?                               | Homework     |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **4**  | **Data tidying and reshaping**                        | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **4**  | **Data types and recoding**                           | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **4**  | **La Quinta is Spanish for 'next to Denny's', Pt. 1** | **Lab**      |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **4**  | **La Quinta is Spanish for 'next to Denny's', Pt. 2** | **Homework** |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 5      | Tips for effective data visualization                 | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 5      | Scientific studies and confounding                    | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 5      | Communicating data science results effectively        | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 5      | Ugly charts                                           | Lab          |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 5      | Legos and instructors                                 | Homework     |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **6**  | **Importing data**                                    | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **6**  | **Web scraping**                                      | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **6**  | **Work on projects**                                  | **Lab**      |
+-------+--------+-------------------------------------------------------+--------------+
| **1** | **6**  | **Project proposal**                                  | **Homework** |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 7      | Functions and iteration                               | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 7      | Exploring data review                                 | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 7      | University of Edinburgh Art Collection                | Lab          |
+-------+--------+-------------------------------------------------------+--------------+
| 1     | 7      | Peer review of project proposals                      | Homework     |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **8**  | **The language of models**                            | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **8**  | **Linear models with a single predictor**             | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **8**  | **Work on projects**                                  | **Lab**      |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **8**  | **Money in politics**                                 | **Homework** |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 9      | Modeling non-linear relationships                     | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 9      | Linear models with multiple predictors                | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 9      | Grading the professor, Pt. 1                          | Lab          |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 9      | Bike rentals in DC                                    | Homework     |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **10** | **Model selection**                                   | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **10** | **Model validation**                                  | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **10** | **Grading the professor, Pt. 2**                      | **Lab**      |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **10** | ***[Not available]***                                 | **Homework** |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 11     | Logistic regression and classification                | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 11     | Quantifying uncertainty                               | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 11     | *[Not available]*                                     | Lab          |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 11     | *[Not available]*                                     | Homework     |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **12** | **Hypothesis testing with randomization**             | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **12** | **Inference overview**                                | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **12** | **So what if you smoke when pregnant?**               | **Lab**      |
+-------+--------+-------------------------------------------------------+--------------+
| **2** | **12** | **Exploring the General Social Survey**               | **Homework** |
+-------+--------+-------------------------------------------------------+--------------+
| 2     | 13     | Simulation based inference review                     | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 3     | 13     | Data science ethics                                   | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 3     | 13     | Working on projects                                   | Lab          |
+-------+--------+-------------------------------------------------------+--------------+
| 3     | 13     | Wrapping up                                           | Homework     |
+-------+--------+-------------------------------------------------------+--------------+
| **3** | **14** | **Interactive data visualization**                    | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **3** | **14** | **Interactive data visualization and reporting**      | **Lecture**  |
+-------+--------+-------------------------------------------------------+--------------+
| **3** | **14** | **Collaborating on GitHub**                           | **Lab**      |
+-------+--------+-------------------------------------------------------+--------------+
| **3** | **14** | **Work on projects**                                  | **Homework** |
+-------+--------+-------------------------------------------------------+--------------+
| 3     | 15     | Bayesian inference                                    | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 3     | 15     | Text analysis                                         | Lecture      |
+-------+--------+-------------------------------------------------------+--------------+
| 3     | 15     | Work on projects                                      | Lab          |
+-------+--------+-------------------------------------------------------+--------------+
| 3     | 15     | Project presentations & write up                      |              |
+-------+--------+-------------------------------------------------------+--------------+
