---
weight: 4
title: "Tech stack"
output: html_document
---

This course teaches computing and statistics to undergraduates with no background 
in either. Managing such a course with students from varied backgrounds doing 
non-trivial computational work is a big technical challenge. This page briefly 
describes the toolkit choices, and the [infrastructure](/20-infrastructure) section 
provides a path forward for instructors who are considering using these tools for 
their own teaching purposes.

- RStudio Cloud: [RStudio Cloud](https://rstudio.cloud/) is a managed cloud 
instance of the RStudio IDE. We recommend having students access RStudio via 
RStudio Cloud as opposed to using a local installation. 
[[Read more]](20-infrastructure/01-rscloud/)
- GitHub: The use of [GitHub](https://github.com/) also goes a long way to help 
students visualize and understand the git process which also aids in student 
buy-in. The web interface allows students to easily view diffs (file changes 
over time) in files they are collaborating on, keep track of commit histories, 
and search both the current state as well as the entire history of the code 
base. Within the classroom GitHub can be thought of as an advanced and flexible 
learning management system (compared to traditional tools like Blackboard or Sakai).
[[Read more]](20-infrastructure/02-github/)
- Slack: [Slack](https://slack.com/) is a versatile communications and 
collaboration tool. Students are discouraged from using email and, most course 
communication happens here. Both public (for announcements and general questions) 
and private (for team communication) channels are used.
[[Read more]](20-infrastructure/03-slack/)
