{
  "hash": "bd1cb585627957697b635dc6d8deb471",
  "result": {
    "markdown": "---\ntitle: \"Modeling non-linear relationships\"\nsubtitle: \"<br><br> Data Science in a Box\"\nauthor: \"[datasciencebox.org](https://datasciencebox.org/)\"\noutput:\n  xaringan::moon_reader:\n    css: [\"../xaringan-themer.css\", \"../slides.css\"]\n    lib_dir: libs\n    anchor_sections: FALSE\n    nature:\n      ratio: \"16:9\"\n      highlightLines: true\n      highlightStyle: solarized-light\n      countIncrementalSlides: false\n---\n\n\n\n\nlayout: true\n  \n<div class=\"my-footer\">\n<span>\n<a href=\"https://datasciencebox.org\" target=\"_blank\">datasciencebox.org</a>\n</span>\n</div> \n\n---\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nclass: middle\n\n# Model checking\n\n\n---\n\n## Data: Paris Paintings\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp <- read_csv(\"data/paris-paintings.csv\", na = c(\"n/a\", \"\", \"NA\"))\n```\n:::\n\n- Number of observations: 3393\n- Number of variables: 61\n\n---\n\n\n## \"Linear\" models\n\n- We're fitting a \"linear\" model, which assumes a linear relationship between our explanatory and response variables.\n- But how do we assess this?\n\n\n---\n\n## Graphical diagnostic: residuals plot\n\n.panelset[\n.panel[.panel-name[Plot]\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=60%}\n:::\n:::\n]\n.panel[.panel-name[Code]\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nht_wt_fit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(Height_in ~ Width_in, data = pp)\n\nht_wt_fit_aug <- augment(ht_wt_fit$fit) #<<\n\nggplot(ht_wt_fit_aug, mapping = aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = 0.5) +\n  geom_hline(yintercept = 0, color = \"gray\", lty = \"dashed\") +\n  labs(x = \"Predicted height\", y = \"Residuals\")\n```\n:::\n]\n\n.panel[.panel-name[Augment]\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nht_wt_fit_aug\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3,135 × 9\n   .rownames Height_in Width_in .fitted  .resid     .hat .sigma\n   <chr>         <dbl>    <dbl>   <dbl>   <dbl>    <dbl>  <dbl>\n 1 1                37     29.5   26.7  10.3    0.000399   8.30\n 2 2                18     14     14.6   3.45   0.000396   8.31\n 3 3                13     16     16.1  -3.11   0.000361   8.31\n 4 4                14     18     17.7  -3.68   0.000337   8.31\n 5 5                14     18     17.7  -3.68   0.000337   8.31\n 6 6                 7     10     11.4  -4.43   0.000498   8.31\n 7 7                 6     13     13.8  -7.77   0.000418   8.30\n 8 8                 6     13     13.8  -7.77   0.000418   8.30\n 9 9                15     15     15.3  -0.333  0.000377   8.31\n10 10                9      7      9.09 -0.0870 0.000601   8.31\n# … with 3,125 more rows, and 2 more variables: .cooksd <dbl>,\n#   .std.resid <dbl>\n```\n:::\n:::\n]\n]\n\n---\n\n\n## More on `augment()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglimpse(ht_wt_fit_aug)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 3,135\nColumns: 9\n$ .rownames  <chr> \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\",…\n$ Height_in  <dbl> 37, 18, 13, 14, 14, 7, 6, 6, 15, 9, 9, 16, 1…\n$ Width_in   <dbl> 29.5, 14.0, 16.0, 18.0, 18.0, 10.0, 13.0, 13…\n$ .fitted    <dbl> 26.65490, 14.55256, 16.11415, 17.67574, 17.6…\n$ .resid     <dbl> 10.3451004, 3.4474447, -3.1141481, -3.675740…\n$ .hat       <dbl> 0.0003991488, 0.0003961825, 0.0003611963, 0.…\n$ .sigma     <dbl> 8.303538, 8.305367, 8.305409, 8.305336, 8.30…\n$ .cooksd    <dbl> 3.099689e-04, 3.416655e-05, 2.541574e-05, 3.…\n$ .std.resid <dbl> 1.24600543, 0.41522347, -0.37507338, -0.4427…\n```\n:::\n:::\n\n---\n\n## Looking for...\n\n- Residuals distributed randomly around 0\n- With no visible pattern along the x or y axes\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n\n## Not looking for...\n\n.large[\n**Fan shapes**\n]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n## Not looking for...\n\n.large[\n**Groups of patterns**\n]\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n\n## Not looking for...\n\n.large[\n**Residuals correlated with predicted values**\n]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n## Not looking for...\n\n.large[\n**Any patterns!**\n]\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n\n.question[\nWhat patterns does the residuals plot reveal that should make us question whether a linear model is a good fit for modeling the relationship between height and width of paintings?\n]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\nclass: middle\n\n# Exploring linearity\n\n---\n\n\n## Data: Paris Paintings\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=70%}\n:::\n:::\n\n---\n\n## Price vs. width\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=70%}\n:::\n:::\n\n---\n\n\n## Focus on paintings with `Width_in < 100`\n\nThat is, paintings with width < 2.54 m\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_wt_lt_100 <- pp %>% \n  filter(Width_in < 100)\n```\n:::\n\n---\n\n## Price vs. width\n\n.question[\nWhich plot shows a more linear relationship?\n]\n\n.small[\n  \n.pull-left[\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n]\n\n.pull-right[\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n:::\n]\n\n]\n\n---\n\n\n## Price vs. width, residuals\n\n.question[\nWhich plot shows a residuals that are uncorrelated with predicted values from the model? Also, what is the unit of the residuals?\n]\n  \n.pull-left[\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n]\n.pull-right[\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n:::\n\n]\n\n\n---\n\n## Transforming the data\n\n- We saw that `price` has a right-skewed distribution, and the relationship between price and width of painting is non-linear.\n\n--\n- In these situations a transformation applied to the response variable may be useful.\n\n--\n- In order to decide which transformation to use, we should examine the distribution of the response variable.\n\n--\n- The extremely right skewed distribution suggests that a log transformation may \nbe useful.\n    - log = natural log, $ln$\n    - Default base of the `log` function in R is the natural log: <br>\n    `log(x, base = exp(1))`\n    \n---\n\n\n## Logged price vs. width\n\n.question[\nHow do we interpret the slope of this model?\n]\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d03-modeling-nonlinear-relationships_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n## Models with log transformation\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(log(price) ~ Width_in, data = pp_wt_lt_100) %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   4.67     0.0585      79.9  0       \n2 Width_in      0.0192   0.00226      8.48 3.36e-17\n```\n:::\n:::\n\n---\n\n\n\n## Interpreting the slope\n\n\n$$ \\widehat{log(price)} = 4.67 + 0.0192 Width $$\n\n\n--\n- For each additional inch the painting is wider, the log price of the painting is expected to be higher, on average, by 0.0192 livres.\n\n--\n- which is not a very useful statement...\n\n\n---\n\n## Working with logs\n\n- Subtraction and logs: $log(a) − log(b) = log(a / b)$\n\n--\n- Natural logarithm: $e^{log(x)} = x$\n\n--\n- We can use these identities to \"undo\" the log transformation\n\n---\n\n\n## Interpreting the slope\n\nThe slope coefficient for the log transformed model is 0.0192, meaning the log price difference between paintings whose widths are one inch apart is predicted to be 0.0192 log livres.\n\n--\n\n.question[\nUsing this information, and properties of logs that we just reviewed, fill in the blanks in the following alternate interpretation of the slope:\n\n>For each additional inch the painting is wider, the price of the painting is expected to be `___` , on average, by a factor of `___`.\n]\n\n\n\n---\n\n>For each additional inch the painting is wider, the price of the painting is expected to be `___` , on average, by a factor of `___`.\n\n\n\n$$ log(\\text{price for width x+1}) - log(\\text{price for width x}) = 0.0192 $$\n\n\n--\n\n\n$$ log\\left(\\frac{\\text{price for width x+1}}{\\text{price for width x}}\\right) = 0.0192 $$\n\n\n--\n\n\n$$ e^{log\\left(\\frac{\\text{price for width x+1}}{\\text{price for width x}}\\right)} = e^{0.0192} $$\n\n\n--\n\n\n$$ \\frac{\\text{price for width x+1}}{\\text{price for width x}} \\approx 1.02 $$\n\n\n--\n\nFor each additional inch the painting is wider, the price of the painting is expected to be higher, on average, by a factor of 1.02.\n\n---\n\n\n## Recap\n\n- Non-constant variance is one of the most common model violations, however it is usually fixable by transforming the response (y) variable.\n\n--\n- The most common transformation when the response variable is right skewed is the log transform: $log(y)$, especially useful when the response variable is \n(extremely) right skewed.\n\n--\n- This transformation is also useful for variance stabilization.\n\n--\n- When using a log transformation on the response variable the interpretation of \nthe slope changes: *\"For each unit increase in x, y is expected on average to be higher/lower <br> by a factor of $e^{b_1}$.\"*\n\n--\n- Another useful transformation is the square root: $\\sqrt{y}$, especially \nuseful when the response variable is counts.\n\n\n---\n\n## Transform, or learn more?\n\n- Data transformations may also be useful when the relationship is non-linear\n- However in those cases a polynomial regression may be more appropriate\n  + This is beyond the scope of this course, but you’re welcomed to try it for your final project, and I’d be happy to provide further guidance\n\n---\n\n\n## Aside: when $y = 0$\n\nIn some cases the value of the response variable might be 0, and\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlog(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -Inf\n```\n:::\n:::\n\n\n--\n\nThe trick is to add a very small number to the value of the response variable for these cases so that the `log` function can still be applied:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlog(0 + 0.00001)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -11.51293\n```\n:::\n:::\n",
    "supporting": [
      "u4-d03-modeling-nonlinear-relationships_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/font-awesome/css/all.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/font-awesome/css/v4-shims.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/panelset/panelset.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/panelset/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}