{
  "hash": "cd2f35e802d5cf508a282e50d6df5cd7",
  "result": {
    "markdown": "---\ntitle: \"Bootstrapping\"\nsubtitle: \"<br><br> Data Science in a Box\"\nauthor: \"[datasciencebox.org](https://datasciencebox.org/)\"\noutput:\n  xaringan::moon_reader:\n    css: [\"../xaringan-themer.css\", \"../slides.css\"]\n    lib_dir: libs\n    anchor_sections: FALSE\n    nature:\n      ratio: \"16:9\"\n      highlightLines: true\n      highlightStyle: solarized-light\n      countIncrementalSlides: false\n---\n\n\n\n\nlayout: true\n  \n<div class=\"my-footer\">\n<span>\n<a href=\"https://datasciencebox.org\" target=\"_blank\">datasciencebox.org</a>\n</span>\n</div> \n\n---\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nclass: middle\n\n# Rent in Edinburgh\n\n\n---\n\n## Rent in Edinburgh\n\n.question[\nTake a guess! How much does a typical 3 BR flat in Edinburgh rents for?\n]\n\n---\n\n\n## Sample\n\nFifteen 3 BR flats in Edinburgh were randomly selected on rightmove.co.uk.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nedi_3br <- read_csv2(\"data/edi-3br.csv\") # ; separated\n```\n:::\n\n\n.small[\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 15 × 4\n  flat_id  rent title                       address              \n  <chr>   <dbl> <chr>                       <chr>                \n1 flat_01   825 3 bedroom apartment to rent Burnhead Grove, Edin…\n2 flat_02  2400 3 bedroom flat to rent      Simpson Loan, Quarte…\n3 flat_03  1900 3 bedroom flat to rent      FETTES ROW, NEW TOWN…\n4 flat_04  1500 3 bedroom apartment to rent Eyre Crescent, Edinb…\n5 flat_05  3250 3 bedroom flat to rent      Walker Street, Edinb…\n6 flat_06  2145 3 bedroom flat to rent      George Street, City …\n# … with 9 more rows\n```\n:::\n:::\n\n]\n\n\n---\n\n## Observed sample\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d11-bootstrap_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=80%}\n:::\n:::\n\n---\n\n\n## Observed sample\n\nSample mean ≈ £1895 😱\n\n<br>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](img/rent-bootsamp.png){fig-align='center' width=90%}\n:::\n:::\n\n---\n\n## Bootstrap population\n\nGenerated assuming there are more flats like the ones in the observed sample... Population mean = ❓\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](img/rent-bootpop.png){fig-align='center' width=65%}\n:::\n:::\n\n---\n\n\n## Bootstrapping scheme\n\n1. Take a bootstrap sample - a random sample taken **with replacement** from the \noriginal sample, of the same size as the original sample\n2. Calculate the bootstrap statistic - a statistic such as mean, median, \nproportion, slope, etc. computed on the bootstrap samples\n3. Repeat steps (1) and (2) many times to create a bootstrap distribution - \na distribution of bootstrap statistics\n4. Calculate the bounds of the XX% confidence interval as the middle XX% \nof the bootstrap distribution\n\n\n---\n\nclass: middle\n\n# Bootstrapping with tidymodels\n\n---\n\n\n## Generate bootstrap means\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nedi_3br %>%\n  # specify the variable of interest\n  specify(response = rent)\n```\n:::\n\n---\n\n## Generate bootstrap means\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nedi_3br %>%\n  # specify the variable of interest\n  specify(response = rent)\n  # generate 15000 bootstrap samples\n  generate(reps = 15000, type = \"bootstrap\")\n```\n:::\n\n---\n\n\n## Generate bootstrap means\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nedi_3br %>%\n  # specify the variable of interest\n  specify(response = rent)\n  # generate 15000 bootstrap samples\n  generate(reps = 15000, type = \"bootstrap\")\n  # calculate the mean of each bootstrap sample\n  calculate(stat = \"mean\")\n```\n:::\n\n---\n\n## Generate bootstrap means\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# save resulting bootstrap distribution\nboot_df <- edi_3br %>%\n  # specify the variable of interest\n  specify(response = rent) %>% \n  # generate 15000 bootstrap samples\n  generate(reps = 15000, type = \"bootstrap\") %>% \n  # calculate the mean of each bootstrap sample\n  calculate(stat = \"mean\")\n```\n:::\n\n---\n\n\n## The bootstrap sample\n\n.question[\nHow many observations are there in `boot_df`? What does each observation represent?\n]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nResponse: rent (numeric)\n# A tibble: 15,000 × 2\n  replicate  stat\n      <int> <dbl>\n1         1 1793.\n2         2 1938.\n3         3 2175 \n4         4 2159.\n5         5 2084 \n6         6 1761 \n# … with 14,994 more rows\n```\n:::\n:::\n\n---\n\n## Visualize the bootstrap distribution\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = boot_df, mapping = aes(x = stat)) +\n  geom_histogram(binwidth = 100) +\n  labs(title = \"Bootstrap distribution of means\")\n```\n\n::: {.cell-output-display}\n![](u4-d11-bootstrap_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n\n## Calculate the confidence interval\n\nA 95% confidence interval is bounded by the middle 95% of the bootstrap distribution.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboot_df %>%\n  summarize(lower = quantile(stat, 0.025),\n            upper = quantile(stat, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  lower upper\n  <dbl> <dbl>\n1 1603. 2213.\n```\n:::\n:::\n\n---\n\n## Visualize the confidence interval\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d11-bootstrap_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=70%}\n:::\n:::\n\n---\n\n\n## Interpret the confidence interval\n\n.question[\nThe 95% confidence interval for the mean rent of three bedroom flats in Edinburgh was calculated as (1603, 2213). Which of the following is the correct interpretation of this interval?\n\n**(a)** 95% of the time the mean rent of three bedroom flats in this sample is between £1603 and £2213.\n\n**(b)** 95% of all three bedroom flats in Edinburgh have rents between £1603 and £2213.\n\n**(c)** We are 95% confident that the mean rent of all three bedroom flats is between £1603 and £2213.\n\n**(d)** We are 95% confident that the mean rent of three bedroom flats in this sample is between £1603 and £2213.\n]\n\n\n---\n\nclass: middle\n\n# Accuracy vs. precision\n\n---\n\n\n## Confidence level\n\n**We are 95% confident that ...**\n\n- Suppose we took many samples from the original population and built a 95% confidence interval based on each sample.\n- Then about 95% of those intervals would contain the true population parameter.\n\n\n---\n\n## Commonly used confidence levels\n\n.question[\nWhich line (orange dash/dot, blue dash, green dot) represents which confidence level?\n]\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d11-bootstrap_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n\n## Precision vs. accuracy\n\n.question[\nIf we want to be very certain that we capture the population parameter, should we use a wider or a narrower interval? What drawbacks are associated with using a wider interval?\n]\n\n--\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](img/garfield.png){fig-align='center' width=60%}\n:::\n:::\n\n\n--\n\n.question[\nHow can we get best of both worlds -- high precision and high accuracy?\n]\n\n\n---\n\n## Changing confidence level\n\n.question[\nHow would you modify the following code to calculate a 90% confidence interval? \nHow would you modify it for a 99% confidence interval?\n]\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nedi_3br %>%\n  specify(response = rent) %>% \n  generate(reps = 15000, type = \"bootstrap\") %>% \n  calculate(stat = \"mean\") %>%\n  summarize(lower = quantile(stat, 0.025),\n            upper = quantile(stat, 0.975))\n```\n:::\n\n---\n\n\n## Recap\n\n- Sample statistic $\\ne$ population parameter, but if the sample is good, it can be a good estimate\n- We report the estimate with a confidence interval, and the width of this interval depends on the variability of sample statistics from different samples from the population\n- Since we can't continue sampling from the population, we bootstrap from the one sample we have to estimate sampling variability\n- We can do this for any sample statistic:\n  - For a mean: `calculate(stat = \"mean\")`\n  - For a median: `calculate(stat = \"median\")`\n  - Learn about calculating bootstrap intervals for other statistics in your homework\n",
    "supporting": [
      "u4-d11-bootstrap_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/font-awesome/css/all.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/font-awesome/css/v4-shims.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/panelset/panelset.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/panelset/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}