{
  "hash": "3bc9de7ef38420688d7d59a1d38940ef",
  "result": {
    "markdown": "---\ntitle: \"More models with multiple predictors\"\nsubtitle: \"<br><br> Data Science in a Box\"\nauthor: \"[datasciencebox.org](https://datasciencebox.org/)\"\noutput:\n  xaringan::moon_reader:\n    css: [\"../xaringan-themer.css\", \"../slides.css\"]\n    lib_dir: libs\n    anchor_sections: FALSE\n    nature:\n      ratio: \"16:9\"\n      highlightLines: true\n      highlightStyle: solarized-light\n      countIncrementalSlides: false\n---\n\n\n\n\nlayout: true\n  \n<div class=\"my-footer\">\n<span>\n<a href=\"https://datasciencebox.org\" target=\"_blank\">datasciencebox.org</a>\n</span>\n</div> \n\n---\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nclass: middle\n\n# Two numerical predictors\n\n\n---\n\n## The data\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp <- read_csv(\n  \"data/paris-paintings.csv\",\n  na = c(\"n/a\", \"\", \"NA\")\n) %>%\n  mutate(log_price = log(price))\n```\n:::\n\n---\n\n\n## Multiple predictors\n\n- Response variable: `log_price` \n- Explanatory variables: Width and height\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_fit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(log_price ~ Width_in + Height_in, data = pp)\ntidy(pp_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   4.77     0.0579      82.4  0       \n2 Width_in      0.0269   0.00373      7.22 6.58e-13\n3 Height_in    -0.0133   0.00395     -3.36 7.93e- 4\n```\n:::\n:::\n\n---\n\n##  Linear model with multiple predictors\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   4.77     0.0579      82.4  0       \n2 Width_in      0.0269   0.00373      7.22 6.58e-13\n3 Height_in    -0.0133   0.00395     -3.36 7.93e- 4\n```\n:::\n:::\n\n<br>\n\n\n$$\\widehat{log\\_price} = 4.77 + 0.0269 \\times width - 0.0133 \\times height$$\n\n\n---\n\n\n## Visualizing models with multiple predictors\n\n.panelset[\n.panel[.panel-name[Plot]\n.pull-left-wide[\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-8f836166d559454ecd73\" style=\"width:100%;height:1483.2px;\" class=\"widgetframe html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8f836166d559454ecd73\">{\"x\":{\"url\":\"u4-d05-more-model-multiple-predictors_files/figure-html//widgets/widget_plotly-plot.html\",\"options\":{\"xdomain\":\"*\",\"allowfullscreen\":false,\"lazyload\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n]\n]\n.panel[.panel-name[Code]\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np <- plot_ly(pp,\n  x = ~Width_in, y = ~Height_in, z = ~log_price,\n  marker = list(size = 3, color = \"lightgray\", alpha = 0.5, \n                line = list(color = \"gray\", width = 2))) %>%\n  add_markers() %>%\n  plotly::layout(scene = list(\n    xaxis = list(title = \"Width (in)\"),\n    yaxis = list(title = \"Height (in)\"),\n    zaxis = list(title = \"log_price\")\n  )) %>%\n  config(displayModeBar = FALSE)\nframeWidget(p)\n```\n:::\n\n]\n]\n\n\n---\n\nclass: middle\n\n# Numerical and categorical predictors\n\n---\n\n\n## Price, surface area, and living artist\n\n- Explore the relationship between price of paintings and surface area, conditioned \non whether or not the artist is still living\n- First visualize and explore, then model\n- But first, prep the data\n\n.midi[\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp <- pp %>%\n  mutate(artistliving = if_else(artistliving == 0, \"Deceased\", \"Living\"))\n\npp %>%\n  count(artistliving)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  artistliving     n\n  <chr>        <int>\n1 Deceased      2937\n2 Living         456\n```\n:::\n:::\n\n]\n\n\n---\n\n## Typical surface area\n\n.panelset[\n.panel[.panel-name[Plot]\n.pull-left-narrow[\nTypical surface area appears to be less than 1000 square inches (~ 80cm x 80cm). There are very few paintings that have surface area above 5000 square inches.\n]\n.pull-right-wide[\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d05-more-model-multiple-predictors_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=90%}\n:::\n:::\n]\n]\n.panel[.panel-name[Code]\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Surface, fill = artistliving)) +\n  geom_histogram(binwidth = 500) + \n  facet_grid(artistliving ~ .) +\n  scale_fill_manual(values = c(\"#E48957\", \"#071381\")) +\n  guides(fill = \"none\") +\n  labs(x = \"Surface area\", y = NULL) +\n  geom_vline(xintercept = 1000) +\n  geom_vline(xintercept = 5000, linetype = \"dashed\", color = \"gray\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 176 rows containing non-finite values\n(stat_bin).\n```\n:::\n:::\n]\n]\n\n---\n\n\n## Narrowing the scope\n\n.panelset[\n.panel[.panel-name[Plot]\nFor simplicity let's focus on the paintings with `Surface < 5000`:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d05-more-model-multiple-predictors_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=55%}\n:::\n:::\n\n]\n.panel[.panel-name[Code]\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_Surf_lt_5000 <- pp %>%\n  filter(Surface < 5000)\n\nggplot(data = pp_Surf_lt_5000, \n       aes(y = log_price, x = Surface, color = artistliving, shape = artistliving)) +\n  geom_point(alpha = 0.5) +\n  labs(color = \"Artist\", shape = \"Artist\") +\n  scale_color_manual(values = c(\"#E48957\", \"#071381\"))\n```\n:::\n\n]\n]\n\n\n---\n\n## Facet to get a better look\n\n.panelset[\n.panel[.panel-name[Plot]\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d05-more-model-multiple-predictors_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n]\n.panel[.panel-name[Code]\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = pp_Surf_lt_5000, \n       aes(y = log_price, x = Surface, color = artistliving, shape = artistliving)) +\n  geom_point(alpha = 0.5) +\n  facet_wrap(~artistliving) +\n  scale_color_manual(values = c(\"#E48957\", \"#071381\")) +\n  labs(color = \"Artist\", shape = \"Artist\")\n```\n:::\n]\n]\n\n---\n\n\n## Two ways to model\n\n- **Main effects:** Assuming relationship between surface and logged price \n**does not vary** by whether or not the artist is living.\n- **Interaction effects:** Assuming relationship between surface and logged \nprice **varies** by whether or not the artist is living.\n\n\n---\n\n## Interacting explanatory variables\n\n- Including an interaction effect in the model allows for different slopes, i.e. \nnonparallel lines.\n- This implies that the regression coefficient for an explanatory variable would \nchange as another explanatory variable changes.\n- This can be accomplished by adding an interaction variable: the product of two \nexplanatory variables.\n\n---\n\n\n## Two ways to model\n\n.pull-left-narrow[\n- **Main effects:** Assuming relationship between surface and logged price **does not vary** by whether or not the artist is living\n- **Interaction effects:** Assuming relationship between surface and logged price **varies** by whether or not the artist is living\n]\n.pull-right-wide[\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d05-more-model-multiple-predictors_files/figure-html/pp-main-int-viz-1.png){fig-align='center' width=70%}\n:::\n:::\n\n]\n\n\n---\n\n## Fit model with main effects\n\n- Response variable: `log_price`\n- Explanatory variables: `Surface` area and `artistliving`\n\n.midi[\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_main_fit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(log_price ~ Surface + artistliving, data = pp_Surf_lt_5000)\ntidy(pp_main_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term               estimate std.error statistic  p.value\n  <chr>                 <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)        4.88     0.0424       115.   0       \n2 Surface            0.000265 0.0000415      6.39 1.85e-10\n3 artistlivingLiving 0.137    0.0970         1.41 1.57e- 1\n```\n:::\n:::\n]\n\n--\n\n\n$$\\widehat{log\\_price} = 4.88 + 0.000265 \\times surface + 0.137 \\times artistliving$$\n\n\n---\n\n\n## Solving the model\n\n- Non-living artist: Plug in 0 for `artistliving`\n\n$\\widehat{log\\_price} = 4.88 + 0.000265 \\times surface + 0.137 \\times 0$  \n$= 4.88 + 0.000265 \\times surface$\n\n--\n- Living artist: Plug in 1 for `artistliving`\n\n$\\widehat{log\\_price} = 4.88 + 0.000265 \\times surface + 0.137 \\times 1$   \n$= 5.017 + 0.000265 \\times surface$\n\n\n---\n\n## Visualizing main effects\n\n.pull-left-narrow[\n- **Same slope:** Rate of change in price as the surface area increases does \nnot vary between paintings by living and non-living artists.\n- **Different intercept:** Paintings by living artists are consistently more \nexpensive than paintings by non-living artists.\n]\n.pull-right-wide[\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d05-more-model-multiple-predictors_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=100%}\n:::\n:::\n]\n\n---\n\n\n## Interpreting main effects\n\n.midi[\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(pp_main_fit) %>% \n  mutate(exp_estimate = exp(estimate)) %>%\n  select(term, estimate, exp_estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  term               estimate exp_estimate\n  <chr>                 <dbl>        <dbl>\n1 (Intercept)        4.88           132.  \n2 Surface            0.000265         1.00\n3 artistlivingLiving 0.137            1.15\n```\n:::\n:::\n\n]\n\n- All else held constant, for each additional square inch in painting's surface area, the price of the painting is predicted, on average, to be higher by a factor of 1.\n- All else held constant, paintings by a living artist are predicted, on average, to be higher by a factor of 1.15 compared to paintings by an artist who is no longer alive.\n- Paintings that are by an artist who is not alive and that have a surface area of 0 square inches are predicted, on average, to be 132 livres.\n\n\n---\n\n## Main vs. interaction effects\n\n- The way we specified our main effects model only lets `artistliving` affect the intercept.\n- Model implicitly assumes that paintings with living and deceased artists have the *same slope* and only allows for *different intercepts*.  \n\n.question[\nWhat seems more appropriate in this case?\n+ Same slope and same intercept for both colours\n+ Same slope and different intercept for both colours\n+ Different slope and different intercept for both colours\n]\n\n---\n\n\n## Interaction: `Surface * artistliving`\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d05-more-model-multiple-predictors_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=60%}\n:::\n:::\n\n---\n\n## Fit model with interaction effects\n\n- Response variable: log_price\n- Explanatory variables: `Surface` area, `artistliving`, and their interaction\n\n.midi[\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_int_fit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(log_price ~ Surface * artistliving, data = pp_Surf_lt_5000)\ntidy(pp_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 5\n  term                       estimate std.error statistic p.value\n  <chr>                         <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)                 4.91e+0 0.0432       114.   0      \n2 Surface                     2.06e-4 0.0000442      4.65 3.37e-6\n3 artistlivingLiving         -1.26e-1 0.119         -1.06 2.89e-1\n4 Surface:artistlivingLiving  4.79e-4 0.000126       3.81 1.39e-4\n```\n:::\n:::\n]\n\n---\n\n\n## Linear model with interaction effects\n\n.midi[\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 5\n  term                       estimate std.error statistic p.value\n  <chr>                         <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)                 4.91e+0 0.0432       114.   0      \n2 Surface                     2.06e-4 0.0000442      4.65 3.37e-6\n3 artistlivingLiving         -1.26e-1 0.119         -1.06 2.89e-1\n4 Surface:artistlivingLiving  4.79e-4 0.000126       3.81 1.39e-4\n```\n:::\n:::\n\n]\n\n\n$$\\widehat{log\\_price} = 4.91 + 0.00021 \\times surface - 0.126 \\times artistliving$$\n\n$$+ ~ 0.00048 \\times surface * artistliving$$\n\n---\n\n## Interpretation of interaction effects\n\n- Rate of change in price as the surface area of the painting increases does \nvary between paintings by living and non-living artists (different slopes), \n- Some paintings by living artists are more expensive than paintings by\nnon-living artists, and some are not (different intercept).\n\n.small[\n.pull-left[\n- Non-living artist: \n$\\widehat{log\\_price} = 4.91 + 0.00021 \\times surface$\n$- 0.126 \\times 0 + 0.00048 \\times surface \\times 0$\n$= 4.91 + 0.00021 \\times surface$\n- Living artist: \n$\\widehat{log\\_price} = 4.91 + 0.00021 \\times surface$\n$- 0.126 \\times 1 + 0.00048 \\times surface \\times 1$\n$= 4.91 + 0.00021 \\times surface$\n$- 0.126 + 0.00048 \\times surface$\n$= 4.784 + 0.00069 \\times surface$\n]\n.pull-right[\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d05-more-model-multiple-predictors_files/figure-html/viz-interaction-effects2-1.png){fig-align='center' width=80%}\n:::\n:::\n]\n]\n\n---\n\n\n## Comparing models\n\nIt appears that adding the interaction actually increased adjusted $R^2$, so we \nshould indeed use the model with the interactions.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(pp_main_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01258977\n```\n:::\n\n```{.r .cell-code}\nglance(pp_int_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01676753\n```\n:::\n:::\n\n---\n\n## Third order interactions\n\n- Can you? Yes\n- Should you? Probably not if you want to interpret these interactions in context\nof the data.\n",
    "supporting": [
      "u4-d05-more-model-multiple-predictors_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/font-awesome/css/all.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/font-awesome/css/v4-shims.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/panelset/panelset.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/panelset/panelset.js\"></script>\n<script src=\"../../../site_libs/htmlwidgets/htmlwidgets.js\"></script>\n<script src=\"../../../site_libs/pymjs/pym.v1.js\"></script>\n<script src=\"../../../site_libs/widgetframe-binding/widgetframe.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}