---
weight: 2
title: "Exploring data"
output: blogdown::html_page
---

## Lectures

- [Meet the toolkit](/slides/u1_d01-meet-the-toolkit/u1_d01-meet-the-toolkit.html) - [<i class="fas fa-code"></i>](https://github.com/rstudio-education/datascience-box/tree/master/slides/u1_d01-meet-the-toolkit)
  - AE 02 - [Bechdel](/appex/ae-02-bechdel/ae-02-bechdel.html) - [<i class="fas fa-code"></i>](https://github.com/rstudio-education/datascience-box/tree/master/appex/ae-02-bechdel) - [<i class="fas fa-cloud"></i>](https://rstudio.cloud/spaces/1655/project/74335)

- [Data and visualization](/slides/u1_d02-data-and-viz/u1_d02-data-and-viz.html) - [<i class="fas fa-code"></i>](https://github.com/rstudio-education/datascience-box/tree/master/slides/u1_d02-data-and-viz)
  - AE 03 - [Starwars](/appex/ae-03-starwars/ae-03-starwars.html) - [<i class="fas fa-code"></i>](https://github.com/rstudio-education/datascience-box/tree/master/appex/ae-03-starwars) - [<i class="fas fa-cloud"></i>](https://rstudio.cloud/spaces/1655/project/74379)

- [Tidy data and data wrangling](/slides/u1_d03-tidy-data-wrangle/u1_d03-tidy-data-wrangle.html) - [<i class="fas fa-code"></i>](https://github.com/rstudio-education/datascience-box/tree/master/slides/u1_d03-tidy-data-wrangle)
  - AE 04 - [NC bike crashes](/appex/ae-04-ncbikecrash/ae-04-ncbikecrash.html) - [<i class="fas fa-code"></i>](https://github.com/rstudio-education/datascience-box/tree/master/appex/ae-04-ncbikecrash) - [<i class="fas fa-cloud"></i>](https://rstudio.cloud/spaces/1655/project/74393)

- [Tips for effective data visualization](/slides/u1_d04-effective-data-viz/u1_d04-effective-data-viz.html)
- [Merge conflicts](/slides/u1_d05-merge-conflicts/u1_d05-merge-conflicts.html) 
- Tips for effective data visualization in R
- [Confounding variables and Simpson's paradox](/slides/u1_d06-confounding-simpsons-paradox/u1_d06-confounding-simpsons-paradox.html)
- [Coding style](/slides/u1_d07-coding-style/u1_d07-coding-style.html)
- [Data types + Recoding variables](/slides/u1_d08-data-class-type-recode/u1_d08-data-class-type-recode.html)
- Review + recap
- [Web scraping](/slides/u1_d09-web-scraping/u1_d09-web-scraping.html)
- [Functions and automation](/slides/u1_d10-functions-and-automation/u1_d10-functions-and-automation.html)

## Labs

- Lab 00 - Logistics: Overview of lab policies; class survey and pretest; create github and RStudio Cloud accounts
- Lab 01 - Hello R!: Working with RStudio Cloud, R, R markdown, and version control
- Lab 02 - Data wrangling and visualization: Summarizing data using ggplot2 and dplyr
- Lab 03 - Visualizing spatial data: Using spatial data to examine the clustering of Denny's restaurants and La Quinta hotels; importance of visualizing spatial data (John Snow)
- Lab 04 - Wrangling spatial data: Working further with the dataset from Lab 03 using new tidyverse functions
- Lab 05 - Simpson's paradox: Review of Simpson's Paradox using data from a study on smoking in Whickham, England

## Homework assignments

- HW 01 - Ugly Charts: Improving a poor data visualization by using the principles discussed in class
- HW 02 - Gotta catch 'em all: Visualizing Pokémon Go data and interpreting the results

