{
  "hash": "667a9832ca459f72be33727947d459d2",
  "result": {
    "markdown": "---\ntitle: \"Models with multiple predictors\"\nsubtitle: \"<br><br> Data Science in a Box\"\nauthor: \"[datasciencebox.org](https://datasciencebox.org/)\"\noutput:\n  xaringan::moon_reader:\n    css: [\"../xaringan-themer.css\", \"../slides.css\"]\n    lib_dir: libs\n    anchor_sections: FALSE\n    nature:\n      ratio: \"16:9\"\n      highlightLines: true\n      highlightStyle: solarized-light\n      countIncrementalSlides: false\n---\n\n\n\n\nlayout: true\n  \n<div class=\"my-footer\">\n<span>\n<a href=\"https://datasciencebox.org\" target=\"_blank\">datasciencebox.org</a>\n</span>\n</div> \n\n---\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nclass: middle\n\n# The linear model with multiple predictors\n\n\n---\n\n## Data: Book weight and volume\n\nThe `allbacks` data frame gives measurements on the volume and weight of 15 books, some of which are paperback and some of which are hardback\n\n.pull-left[\n- Volume - cubic centimetres\n- Area - square centimetres\n- Weight - grams\n]\n.pull-right[\n.small[\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 15 × 4\n   volume  area weight cover\n    <dbl> <dbl>  <dbl> <fct>\n 1    885   382    800 hb   \n 2   1016   468    950 hb   \n 3   1125   387   1050 hb   \n 4    239   371    350 hb   \n 5    701   371    750 hb   \n 6    641   367    600 hb   \n 7   1228   396   1075 hb   \n 8    412     0    250 pb   \n 9    953     0    700 pb   \n10    929     0    650 pb   \n11   1492     0    975 pb   \n12    419     0    350 pb   \n13   1010     0    950 pb   \n14    595     0    425 pb   \n15   1034     0    725 pb   \n```\n:::\n:::\n]\n]\n\n.footnote[\n.small[\nThese books are from the bookshelf of J. H. Maindonald at Australian National University.\n]\n]\n\n---\n\n\n## Book weight vs. volume\n\n.pull-left[\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(weight ~ volume, data = allbacks) %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic    p.value\n  <chr>          <dbl>     <dbl>     <dbl>      <dbl>\n1 (Intercept)  108.      88.4         1.22 0.245     \n2 volume         0.709    0.0975      7.27 0.00000626\n```\n:::\n:::\n\n]\n.pull-right[\n\n::: {.cell layout-align=\"right\"}\n::: {.cell-output-display}\n![](u4-d04-model-multiple-predictors_files/figure-html/unnamed-chunk-4-1.png){fig-align='right' width=75%}\n:::\n:::\n\n]\n\n\n---\n\n## Book weight vs. volume and cover\n\n.pull-left[\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(weight ~ volume + cover, data = allbacks) %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic      p.value\n  <chr>          <dbl>     <dbl>     <dbl>        <dbl>\n1 (Intercept)  198.      59.2         3.34 0.00584     \n2 volume         0.718    0.0615     11.7  0.0000000660\n3 coverpb     -184.      40.5        -4.55 0.000672    \n```\n:::\n:::\n]\n.pull-right[\n::: {.cell layout-align=\"right\"}\n::: {.cell-output-display}\n![](u4-d04-model-multiple-predictors_files/figure-html/unnamed-chunk-6-1.png){fig-align='right' width=75%}\n:::\n:::\n]\n\n---\n\n\n## Interpretation of estimates\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic      p.value\n  <chr>          <dbl>     <dbl>     <dbl>        <dbl>\n1 (Intercept)  198.      59.2         3.34 0.00584     \n2 volume         0.718    0.0615     11.7  0.0000000660\n3 coverpb     -184.      40.5        -4.55 0.000672    \n```\n:::\n:::\n\n\n--\n- **Slope - volume:** *All else held constant*, for each additional cubic centimetre books are larger in volume, we would expect the weight to be higher, on average, by 0.718 grams.\n\n--\n- **Slope - cover:** *All else held constant*, paperback books are weigh, on average, by 184 grams less than hardcover books.\n\n--\n- **Intercept:** Hardcover books with 0 volume are expected to weigh 198 grams, on average. (Doesn't make sense in context.)\n\n\n\n---\n\n## Main vs. interaction effects\n\n.question[\nSuppose we want to predict weight of books from their volume and cover type \n(hardback vs. paperback). Do you think a model with main effects or \ninteraction effects is more appropriate? Explain your reasoning.\n\n**Hint:** Main effects would mean rate at which weight changes as volume \nincreases would be the same for hardback and paperback books and interaction \neffects would mean the rate at which weight changes as volume \nincreases would be different for hardback and paperback books.\n]\n\n---\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d04-model-multiple-predictors_files/figure-html/book-main-int-1.png){fig-align='center' width=65%}\n:::\n:::\n\n---\n\n## In pursuit of Occam's razor\n\n- Occam's Razor states that among competing hypotheses that predict equally well, the one with the fewest assumptions should be selected.\n\n--\n- Model selection follows this principle.\n\n--\n- We only want to add another variable to the model if the addition of that variable brings something valuable in terms of predictive power to the model.\n\n--\n- In other words, we prefer the simplest best model, i.e. **parsimonious** model.\n\n---\n\n\n.pull-left[\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](u4-d04-model-multiple-predictors_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n:::\n\n]\n.pull-right[\n.question[\nVisually, which of the two models is preferable under Occam's razor?\n]\n]\n\n\n---\n\n## R-squared\n\n- $R^2$ is the percentage of variability in the response variable explained by \nthe regression model.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(book_main_fit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9274776\n```\n:::\n\n```{.r .cell-code}\nglance(book_int_fit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9297137\n```\n:::\n:::\n\n--\n- Clearly the model with interactions has a higher $R^2$.\n\n--\n- However using $R^2$ for model selection in models with multiple explanatory variables is not a good idea as $R^2$ increases when **any** variable is added to the model.\n\n---\n\n\n## Adjusted R-squared\n\n... a (more) objective measure for model selection\n\n- Adjusted $R^2$ doesn't increase if the new variable does not provide any new \ninformaton or is completely unrelated, as it applies a penalty for number of \nvariables included in the model.\n- This makes adjusted $R^2$ a preferable metric for model selection in multiple\nregression models.\n\n\n---\n\n## Comparing models\n\n.pull-left[\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(book_main_fit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9274776\n```\n:::\n\n```{.r .cell-code}\nglance(book_int_fit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9297137\n```\n:::\n:::\n]\n.pull-right[\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(book_main_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9153905\n```\n:::\n\n```{.r .cell-code}\nglance(book_int_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9105447\n```\n:::\n:::\n]\n\n--\n\n.pull-left-wide[\n.small[\n- Is R-sq higher for int model?\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(book_int_fit)$r.squared > glance(book_main_fit)$r.squared \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n- Is R-sq adj. higher for int model?\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(book_int_fit)$adj.r.squared > glance(book_main_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n]\n]\n",
    "supporting": [
      "u4-d04-model-multiple-predictors_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/font-awesome/css/all.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/font-awesome/css/v4-shims.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/panelset/panelset.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/panelset/panelset.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}