---
title: "Lab 02 - Plastic waste"
author: "YOUR TEAM NAME"
date: "TODAY'S DATE"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
plastic_waste <- read_csv("data/plastic-waste.csv")
```

### Exercise 1

(Insert narrative here.)

```{r plastic-waste-continent}
# insert code here
```

### Exercise 2

```{r plastic-waste-density}
# insert code here
```

### Exercise 3

(Insert narrative here.)

### Exercise 4

(Insert narrative here.)

```{r plastic-waste-violin}
# insert code here
```

### Exercise 5

(Insert narrative here.)

```{r plastic-waste-mismanaged}
# insert code here
```

### Exercise 6

(Insert narrative here.)

```{r plastic-waste-mismanaged-continent}
# insert code here
```

### Exercise 7

(Insert narrative here.)

```{r plastic-waste-population-total}
# insert code here
```

```{r plastic-waste-population-coastal}
# insert code here
```

### Exercise 8

(Insert narrative here.)

```{r recreate-viz}
# insert code here
```
